// ----------------------------------------------------------------------

export const title = [
  'RESEARCH',
  'Nano Generators and Green Energy',
  'Battery and Energy storage',
  'Project and..',
  '...',
  'RD.',
  'Goal',
  'Approach',
  'Selected Publications',
  'What is soft robotics?',
];

export const sentence = [
  'Assumenda nam repudiandae rerum fugiat vel maxime.',
  'Quis veniam aut saepe aliquid nulla.',
  'Reprehenderit ut voluptas sapiente ratione nostrum est.',
  'Error ut sit vel molestias velit.',
  'Quo quia sit nihil nemo doloremque et.',
  'Autem doloribus harum vero laborum.',
  'Tempora officiis consequuntur architecto nostrum autem nam adipisci.',
  'Voluptas sunt magni adipisci praesentium saepe.',
  'Ea architecto quas voluptates voluptas earum illo est vel rem.',
  'Ipsum expedita reiciendis ut.',
  'Architecto vel voluptatibus alias a aut non maxime ipsa voluptates.',
  'Reiciendis enim officiis cupiditate eaque distinctio laudantium modi similique consequatur.',
  'Ab autem consequatur itaque mollitia ipsum cupiditate error repudiandae nobis.',
  'Distinctio architecto debitis eligendi consequatur unde id modi accusantium possimus.',
  'At ut voluptate accusantium.',
  'Repudiandae ut qui veritatis sint.',
  'Laboriosam blanditiis quo sed et qui esse ipsam necessitatibus sed.',
  'Et molestiae et excepturi maxime omnis.',
  'Sint dolorem quam eum magnam.',
  'Rerum ut iusto iste quam voluptatem necessitatibus.',
  'Et quam in.',
  'Fugit esse tenetur.',
  'Dolorem dolor porro nihil cupiditate molestiae deserunt ut.',
  'Omnis beatae eos eius aut molestias laboriosam laborum et optio.',
  'Ut veniam quam assumenda ut voluptatibus ducimus accusamus.',
  'Quos dignissimos neque omnis reiciendis voluptatem ducimus.',
  'Laboriosam quia ut esse.',
  'Sit reiciendis nihil qui molestias et.',
  'Facilis cupiditate minima ratione quaerat omnis velit non ex totam.',
  'Provident sint esse voluptatem voluptas eveniet est.',
  'Molestias consequatur ea facilis.',
  'Tempora voluptatibus autem ut ut porro quae delectus dolorum.',
  'Et consequatur amet nemo ducimus voluptatem placeat voluptas.',
  'Modi iste atque hic voluptas sit quis deleniti quas consequatur.',
  'Omnis est aliquid odio mollitia aliquid ex.',
  'Officia possimus veniam quod molestias.',
  'Mollitia inventore recusandae provident aut.',
  'Numquam ullam beatae possimus.',
  'Fuga velit cupiditate ex culpa odio aut ut.',
  'Vero corrupti nam voluptatum excepturi est et.',
];

export const description = [
  'We focus on the development of soft actuators and artificial muscle, which can be applied to intra/extra human body robotics, haptic-feedback systems, wearable power suits, and flexible and soft electronics.',
  'Multi-responsive soft actuators',
  'High bending strain and blocking force',
  'Design of active electrode materials with enhanced electrochemical properties',
  'Multifunctionalities into the electrode material',
  'Design of novel architectural configuration for soft actuators',
  'S. Oh, R. Tabassian, P. Thangasamy, M. Mahato, V. H. Nguyen, S. Nam, Z. Huapeng, and I.-K. Oh* Cooling-Accelerated Nanowire-Nitinol Hybrid Muscle for Versatile Prosthetic Hand and Biomimetic Retractable Claw ADVANCED FUNCTIONAL MATERIALS, Vol. 32, Issue 18 (2022) Selected as inside front cover image https://doi.org/10.1002/adfm.202111145',
];
